# Generated by Django 4.2.30 on 2026-08-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_batchconfiguration_studentbatchupload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('credit', models.PositiveIntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'programme_curriculum_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_type', models.CharField(max_length=20, null=True)),
                ('working_year', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'course_registration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'course_replacement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublishedResultStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'examination_publishedresultstudent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField()),
                ('semester_type', models.CharField(max_length=20, null=True)),
                ('announced', models.BooleanField(default=False)),
                ('per_student_selection', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'examination_resultannouncement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=2016)),
                ('roll_no', models.TextField()),
                ('grade', models.TextField()),
                ('batch', models.IntegerField(default=2021)),
                ('academic_year', models.CharField(max_length=9, null=True)),
                ('semester_type', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'online_cms_student_grades',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='archivelog',
            name='performed_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
