# Generated by Django 4.2.30 on 2026-08-02 16:22

from django.db import migrations, models
import iam.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IamToken',
            fields=[
                ('key', models.CharField(default=iam.models._make_key, max_length=48, primary_key=True, serialize=False)),
                ('erp_user_id', models.IntegerField(db_index=True)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'iam_token',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('outcome', models.CharField(max_length=24)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'iam_login_attempt',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(db_index=True, max_length=155)),
                ('permission', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'iam_role_permission',
            },
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('designation', 'permission'), name='iam_role_permission_unique'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['username', '-at'], name='iamattempt_user_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='iamtoken',
            index=models.Index(fields=['erp_user_id', '-created_at'], name='iamtoken_user_recent_idx'),
        ),
    ]
