# Generated by Django 4.2.30 on 2026-08-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IamDesignationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(db_index=True, max_length=155)),
                ('module_code', models.CharField(max_length=48)),
            ],
            options={
                'db_table': 'iam_designation_module',
            },
        ),
        migrations.CreateModel(
            name='IamUser',
            fields=[
                ('erp_user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=300)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('kind', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('compounder', 'Compounder')], db_index=True, default='staff', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('password_hash', models.CharField(blank=True, max_length=128)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('programme', models.CharField(blank=True, max_length=40)),
                ('discipline', models.CharField(blank=True, db_index=True, max_length=40)),
                ('batch_year', models.IntegerField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'iam_user',
            },
        ),
        migrations.CreateModel(
            name='IamUserDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_user_id', models.IntegerField(db_index=True)),
                ('designation', models.CharField(db_index=True, max_length=155)),
            ],
            options={
                'db_table': 'iam_user_designation',
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=12)),
                ('users_seen', models.IntegerField(default=0)),
                ('users_written', models.IntegerField(default=0)),
                ('designations_written', models.IntegerField(default=0)),
                ('module_grants_written', models.IntegerField(default=0)),
                ('deactivated', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'iam_sync_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='iamuserdesignation',
            constraint=models.UniqueConstraint(fields=('erp_user_id', 'designation'), name='iam_user_designation_unique'),
        ),
        migrations.AddIndex(
            model_name='iamuser',
            index=models.Index(fields=['kind', 'discipline'], name='iamuser_kind_disc_idx'),
        ),
        migrations.AddIndex(
            model_name='iamuser',
            index=models.Index(fields=['is_active'], name='iamuser_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='iamdesignationmodule',
            constraint=models.UniqueConstraint(fields=('designation', 'module_code'), name='iam_designation_module_unique'),
        ),
    ]
