# Generated by Django 4.2.30 on 2026-08-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_iamdesignationmodule_iamuser_iamuserdesignation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IamServiceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'iam_service_token',
                'ordering': ['name'],
            },
        ),
    ]
