# Generated by Django 4.2.30 on 2026-08-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0003_iamservicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncrun',
            name='academics_written',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='IamUserAcademic',
            fields=[
                ('erp_user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('roll_no', models.CharField(db_index=True, max_length=32)),
                ('cpi', models.DecimalField(decimal_places=1, max_digits=4)),
                ('earned_credits', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('cpi_denominator_credits', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('active_backlogs', models.IntegerField(default=0)),
                ('courses_counted', models.IntegerField(default=0)),
                ('semester', models.IntegerField()),
                ('semester_type', models.CharField(blank=True, max_length=20)),
                ('declared_seq', models.IntegerField(db_index=True)),
                ('erp_announcement_id', models.IntegerField(blank=True, null=True)),
                ('programme', models.CharField(blank=True, max_length=40)),
                ('computed_by', models.CharField(blank=True, max_length=64)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'iam_user_academic',
                'indexes': [models.Index(fields=['cpi'], name='iamacad_cpi_idx'), models.Index(fields=['active_backlogs'], name='iamacad_backlog_idx')],
            },
        ),
    ]
