# Generated by Django 4.2.30 on 2026-08-08 15:27

from django.db import migrations, models

# Frozen snapshot of iam.erp_source.MODULE_COLUMNS at the time of this migration.
# Copied rather than imported: a migration must describe the past, and importing
# live code would make this backfill change meaning as that list changes.
ERP_PROJECTED = (
    "placement_cell", "hr", "mess_management", "hostel_management",
    "complaint_management", "phc", "visitor_hostel", "gymkhana", "iwd",
    "rspc", "purchase_and_store",
)


def backfill_source(apps, schema_editor):
    """Existing rows default to erp; the ones the projection never wrote are not."""
    apps.get_model("iam", "IamDesignationModule").objects.exclude(
        module_code__in=ERP_PROJECTED).update(source="manifest")


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0005_iamtoken_key_hashed'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='iamdesignationmodule',
            name='iam_designation_module_unique',
        ),
        migrations.AddField(
            model_name='iamdesignationmodule',
            name='source',
            field=models.CharField(choices=[('erp', 'ERP projection'), ('manifest', 'Service manifest')], default='erp', max_length=16),
        ),
        migrations.RunPython(backfill_source, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='iamdesignationmodule',
            constraint=models.UniqueConstraint(fields=('designation', 'module_code', 'source'), name='iam_designation_module_unique'),
        ),
    ]
