# Generated by Django 4.2.30 on 2026-08-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0006_designation_module_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='IamRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=155, unique=True)),
                ('label', models.CharField(blank=True, max_length=155)),
                ('category', models.CharField(choices=[('basic', 'Basic role — what a person is'), ('rank', 'Academic rank'), ('office', 'Office held'), ('functional', 'Functional role')], max_length=16)),
                ('allowed_kinds', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'iam_role',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='IamRoleViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_user_id', models.IntegerField(db_index=True)),
                ('username', models.CharField(max_length=150)),
                ('kind', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=155)),
                ('enforced', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'iam_role_violation',
                'ordering': ['username', 'designation'],
            },
        ),
        migrations.AddField(
            model_name='syncrun',
            name='role_violations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='iamroleviolation',
            constraint=models.UniqueConstraint(fields=('erp_user_id', 'designation'), name='iam_role_violation_unique'),
        ),
    ]
