# Generated by Django 4.2.30 on 2026-08-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0007_role_catalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iamuser',
            name='kind',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('compounder', 'Compounder'), ('unknown', 'Unclassified')], db_index=True, default='unknown', max_length=20),
        ),
    ]
